/* ======================================================
   HAIR Lab — Embedded dataset
   Lets the site run by double-click (file://) without a server,
   since browsers block fetch() of local JSON files.
   common.js fetchJSON() reads from here first.
   Generated by tools/build-data.js — edit there, not here.
   ====================================================== */
window.HAIR_DATA = {
  "members": [
    {
      "id": "prof-kim",
      "role": "Professor",
      "name": "Keeheon Lee",
      "title": "Full Professor · Principal Investigator",
      "country": "South Korea",
      "flag": "🇰🇷",
      "department": "Underwood International College (UIC), Yonsei University",
      "image": "images/avatars/prof-kim.svg",
      "interests": [
        "Human–AI Interaction & Trust",
        "Computational Social Science",
        "AI for Social Good"
      ],
      "bio": "Keeheon Lee (이기헌) is a Full Professor at Underwood International College and the Department of Innovation, Yonsei Graduate School, who introduces himself as “a data scientist for (social) good.” He devotes himself to finding ways for data and AI to genuinely help people and society, and he enjoys education and new endeavors as much as research. He personally launched the Design Intelligence program at the Graduate School of Communication — which carried over into today's graduate program of the Department of Innovation — and planned Makerspace i7 himself, starting from the proposal.",
      "email": "keeheon@yonsei.ac.kr",
      "website": "https://sites.google.com/yonsei.ac.kr/professor-keeheon/keeheon-lee-yonsei-university",
      "scholar": "https://scholar.google.com/citations?user=DM09eoQAAAAJ&hl=ko&oi=ao",
      "cv": {
        "specializations": [
          "Professor, Creative Technology Management, Underwood International College (UIC)",
          "Professor, Department of Innovation, Yonsei Graduate School",
          "Professor, Digital Analytics Interdisciplinary Program (M.S.), College of Computing",
          "Adjunct Professor, Graduate School of Information"
        ],
        "positions": [
          {
            "text": "Director, Humanities, Arts, and Social Sciences Division, UIC"
          },
          {
            "text": "Program Chair, Department of Innovation, Yonsei Graduate School"
          },
          {
            "text": "Associate Dean of Planning, University College",
            "date": "2026.03–"
          },
          {
            "text": "Principal Investigator, Institute for AI and Social Innovation"
          },
          {
            "text": "Associate Director, Makerspace i7",
            "date": "2025.09–"
          }
        ],
        "career": [
          {
            "text": "Visiting Professor, Mechanical & Industrial Engineering, University of Toronto",
            "date": "2023.09–2024.08"
          },
          {
            "text": "Director, Yonsei Digital Experience Center",
            "date": "2022–2023"
          },
          {
            "text": "Associate Director, Veritas Research Institute",
            "date": "2021–2023"
          },
          {
            "text": "Associate Director, Makerspace i7",
            "date": "2022.03–2022.08"
          },
          {
            "text": "Steering Committee — Design Factory Korea · Makerspace i7 · Global Engagement & Empowerment Forum"
          },
          {
            "text": "Sustainable Development Fellow, Institute for Global Engagement & Empowerment"
          }
        ],
        "awards": [
          {
            "text": "QS Reimagine Education Award — Bronze, Social Science",
            "date": "2021"
          },
          {
            "text": "Outstanding Faculty Achievement Award, Yonsei University"
          }
        ],
        "teaching": {
          "graduate": [
            {
              "text": "Computational Linguistics and Innovation in Technology",
              "date": "2024–2026"
            },
            {
              "text": "Understanding Sustainable Development (지속가능발전의이해)",
              "date": "2022–2026"
            },
            {
              "text": "Business Intelligence",
              "date": "2022–2025"
            },
            {
              "text": "AI and Credit Scoring Models (인공지능과 신용평가 모델)",
              "date": "2025"
            },
            {
              "text": "Human-Centered Technology Policy (인간중심 기술정책)",
              "date": "2024"
            },
            {
              "text": "Advanced Topics in Deep Learning",
              "date": "2023"
            },
            {
              "text": "Entrepreneurship: Startup & Management (창업과 경영)",
              "date": "2023"
            },
            {
              "text": "Deep Learning Theory and Practice (딥러닝 이론과 실습)",
              "date": "2022"
            },
            {
              "text": "Innovation Research 2",
              "date": "2022"
            },
            {
              "text": "Methods of Innovation Research: Quantitative Methods",
              "date": "2021–2022"
            },
            {
              "text": "Computer Vision (컴퓨터비전)",
              "date": "2021"
            },
            {
              "text": "Human–AI Interaction Research Project I–II",
              "date": "2019–2020"
            },
            {
              "text": "AI for UX Design (UX디자인을 위한 인공지능)",
              "date": "2019"
            },
            {
              "text": "Introduction to Design Intelligence (디자인인텔리전스개론)",
              "date": "2019"
            },
            {
              "text": "IoT Foundation I–II (사물인터넷 기초)",
              "date": "2017–2020"
            },
            {
              "text": "Data Science 1: Analytics (데이터과학: 분석)",
              "date": "2018"
            },
            {
              "text": "R&D and New Product Development Management",
              "date": "2015"
            }
          ],
          "undergraduate": [
            {
              "text": "Understanding Sustainable Development with Ban Ki-moon (반기문과 함께하는 지속가능발전의 이해)",
              "date": "2021–2026"
            },
            {
              "text": "Social Network Analysis",
              "date": "2016–2025"
            },
            {
              "text": "Empirical Methods in NLP for Technology Management",
              "date": "2025"
            },
            {
              "text": "Network Science for Creative Industry",
              "date": "2024"
            },
            {
              "text": "Data Science for Business",
              "date": "2017–2023"
            },
            {
              "text": "Programming for Everybody",
              "date": "2018–2023"
            },
            {
              "text": "Introduction to Python Programming",
              "date": "2020–2023"
            },
            {
              "text": "IT Foundation",
              "date": "2016–2022"
            },
            {
              "text": "Techno-Art Capstone Project",
              "date": "2018–2026"
            },
            {
              "text": "Sophomore Career Seminar (Creative Technology Management)",
              "date": "2026"
            },
            {
              "text": "Operations Research and Management Science for CTM",
              "date": "2022"
            },
            {
              "text": "Creative Technology for Social Innovation",
              "date": "2022"
            },
            {
              "text": "Social Innovation Capstone Project 2",
              "date": "2017–2018"
            },
            {
              "text": "Leadership Seminar in Techno-Art Entrepreneurship",
              "date": "2018–2019"
            },
            {
              "text": "Smart Service Systems",
              "date": "2017"
            },
            {
              "text": "Everyday Computing and the Internet",
              "date": "2017"
            },
            {
              "text": "User Experience Design",
              "date": "2019"
            },
            {
              "text": "Undergraduate Directed Study",
              "date": "2020–2022"
            }
          ]
        }
      }
    },
    {
      "id": "ryu-kunhee",
      "role": "Lab Manager",
      "title": "Associate Manager & Lab Manager",
      "name": "Kunhee Ryu",
      "nameKo": "류건희",
      "affil": "CTM '19 · M.S. Innovation '23",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/ryu-kunhee.svg",
      "bio": "Kunhee Ryu is the Lab Manager and Associate Manager of HAIR Lab and a graduate researcher in Innovation. He co-authors the lab's work on multi-agent LLM systems, autonomous meta-analysis (AutoMETA), and human–AI interaction & trust."
    },
    {
      "id": "lee-sooyoung",
      "role": "Ph.D. Student",
      "name": "Sooyoung Lee",
      "nameKo": "이수영",
      "affil": "Ph.D. · Science & Technology Policy",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/lee-sooyoung.svg",
      "bio": "Sooyoung Lee is a Ph.D. student in Science and Technology Policy at HAIR Lab."
    },
    {
      "id": "park-seongwon",
      "role": "Ph.D. Student",
      "name": "Seongwon Park",
      "nameKo": "박성원",
      "affil": "Ph.D. · Science & Technology Policy",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/park-seongwon.svg",
      "bio": "Seongwon Park is a Ph.D. student in Science and Technology Policy at HAIR Lab."
    },
    {
      "id": "kim-minje",
      "role": "Researcher",
      "name": "Minje Kim",
      "nameKo": "김민제",
      "affil": "Econ & CTM '19 · M.S. Innovation '23",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/kim-minje.svg",
      "bio": "Minje Kim completed an M.S. in Innovation and is a researcher at HAIR Lab, working on privacy in LLM agents and multi-agent norm dynamics."
    },
    {
      "id": "svetasheva-arina",
      "role": "Researcher",
      "name": "Arina Svetasheva",
      "affil": "M.S. Innovation '23",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/svetasheva-arina.svg",
      "bio": "Arina Svetasheva completed an M.S. in Innovation and is a researcher at HAIR Lab, working on large language models for effective and efficient hate-speech detection."
    },
    {
      "id": "gasparini-abebe",
      "role": "Researcher",
      "name": "Abebe Gasparini",
      "affil": "M.S. Innovation '23",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/gasparini-abebe.svg",
      "bio": "Abebe Gasparini completed an M.S. in Innovation and is a researcher at HAIR Lab."
    },
    {
      "id": "farias-lucas",
      "role": "M.S. Student",
      "name": "Lucas Farias",
      "affil": "M.S. Innovation",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/farias-lucas.svg",
      "bio": "Lucas Farias is an M.S. student in Innovation at HAIR Lab."
    },
    {
      "id": "marry-anne",
      "role": "M.S. Student",
      "name": "Marry Anne",
      "affil": "M.S. Innovation",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/marry-anne.svg",
      "bio": "Marry Anne is an M.S. student in Innovation at HAIR Lab."
    },
    {
      "id": "aguilar-daniela",
      "role": "M.S. Student",
      "name": "Daniela Rocio Aguilar de La Torre",
      "affil": "M.S. Innovation",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/aguilar-daniela.svg",
      "bio": "Daniela Rocio Aguilar de La Torre is an M.S. student in Innovation at HAIR Lab."
    },
    {
      "id": "lee-jinho",
      "role": "M.S. Student",
      "name": "Jinho Lee",
      "nameKo": "이진호",
      "affil": "M.S. Digital Analytics",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/lee-jinho.svg",
      "bio": "Jinho Lee is an M.S. student in Digital Analytics at HAIR Lab."
    },
    {
      "id": "koo-joonhui",
      "role": "Intern",
      "name": "Joonhui Koo",
      "nameKo": "구준회",
      "affil": "Research Intern",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/koo-joonhui.svg",
      "bio": "Joonhui Koo is a research intern at HAIR Lab."
    },
    {
      "id": "nemo-chowchuvech",
      "role": "Undergraduate Researcher",
      "name": "Wutthipat Chowchuvech",
      "affil": "CTM '24",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/nemo-chowchuvech.svg",
      "bio": "Wutthipat Chowchuvech is an undergraduate researcher (Creative Technology Management) at HAIR Lab."
    },
    {
      "id": "yoo-hogyun",
      "role": "Undergraduate Researcher",
      "name": "Hogyun Yoo",
      "nameKo": "유호균",
      "affil": "CTM '22",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/yoo-hogyun.svg",
      "bio": "Hogyun Yoo is an undergraduate researcher (Creative Technology Management) at HAIR Lab."
    },
    {
      "id": "hwang-seongjoon",
      "role": "Undergraduate Researcher",
      "name": "Seongjoon Hwang",
      "nameKo": "황성준",
      "affil": "CTM '24",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/hwang-seongjoon.svg",
      "bio": "Seongjoon Hwang is an undergraduate researcher (Creative Technology Management) at HAIR Lab."
    },
    {
      "id": "tae-gayeong",
      "role": "Undergraduate Researcher",
      "name": "Gayeong Tae",
      "nameKo": "태가영",
      "affil": "CTM '23",
      "department": "Underwood International College, Yonsei University",
      "image": "images/avatars/tae-gayeong.svg",
      "bio": "Gayeong Tae is an undergraduate researcher (Creative Technology Management) at HAIR Lab."
    }
  ],
  "news": [
    {
      "id": "news-1",
      "slug": "chi-2026-accepted",
      "title": "Two HAIR Lab papers accepted at CHI 2026",
      "date": "2026-01-20",
      "author": "Keeheon Lee",
      "authorId": "prof-kim",
      "summary": "Work on reframing clinician trust in AI and on second-hand privacy harms in LLM agents will appear at CHI 2026.",
      "content": "We are delighted to share that two papers from HAIR Lab have been accepted to the ACM CHI Conference on Human Factors in Computing Systems (CHI 2026). “Can Transparency Help Clinicians Trust AI? Reframing Trust as an Information Foraging and Sensemaking Loop” reconsiders how transparency shapes trust, while “Your Permission Leaks My Data: Second-Hand Privacy Harms in LLM Agents” examines emerging privacy risks in agentic systems. Congratulations to everyone involved!",
      "image": "images/default_news.svg",
      "relatedMembers": [
        "prof-kim",
        "ryu-kunhee",
        "kim-minje"
      ],
      "relatedProjects": [
        "decision-intelligence"
      ]
    },
    {
      "id": "news-2",
      "slug": "autometa-aamas-2026",
      "title": "AutoMETA accepted at AAMAS 2026",
      "date": "2026-01-10",
      "author": "Keeheon Lee",
      "authorId": "prof-kim",
      "summary": "Our multi-agent LLM system for autonomous meta-analysis will be presented at AAMAS 2026.",
      "content": "Our paper “AutoMETA: A Multi-Agent LLM System for Autonomous Meta-Analysis” has been accepted at the International Conference on Autonomous Agents and Multiagent Systems (AAMAS 2026). AutoMETA coordinates multiple LLM agents to carry out the stages of a meta-analysis with minimal human intervention — part of the lab’s broader work on AI for science and meta-research.",
      "image": "images/default_news.svg",
      "relatedMembers": [
        "prof-kim",
        "ryu-kunhee"
      ],
      "relatedProjects": [
        "governance-digital-twin"
      ]
    },
    {
      "id": "news-3",
      "slug": "giq-ai-governance-2025",
      "title": "AI-governance paper published in Government Information Quarterly",
      "date": "2025-09-05",
      "author": "Keeheon Lee",
      "authorId": "prof-kim",
      "summary": "A study on harmonizing AI ethics guidelines with legal frameworks in Korea appears in Government Information Quarterly.",
      "content": "Our paper “Building a consensus: Harmonizing AI ethical guidelines and legal frameworks in Korea for enhanced governance” has been published in Government Information Quarterly, a leading journal in digital government. The work proposes how AI ethics principles can be reconciled with existing legal systems to enable more effective governance.",
      "image": "images/default_news.svg",
      "relatedMembers": [
        "prof-kim"
      ],
      "relatedProjects": [
        "decision-intelligence"
      ]
    },
    {
      "id": "news-4",
      "slug": "hate-speech-llm-hicss-2024",
      "title": "LLMs for hate-speech detection presented at HICSS 2024",
      "date": "2024-01-08",
      "author": "Keeheon Lee",
      "authorId": "prof-kim",
      "summary": "Our study on harnessing large language models for effective and efficient hate-speech detection was presented at HICSS 2024.",
      "content": "At the Hawaii International Conference on System Sciences (HICSS 2024), we presented “Harnessing Large Language Models for Effective and Efficient Hate Speech Detection,” showing how LLMs can improve both the accuracy and the efficiency of detecting hate speech — part of our NLP-for-social-good agenda.",
      "image": "images/default_news.svg",
      "relatedMembers": [
        "prof-kim",
        "svetasheva-arina"
      ],
      "relatedProjects": [
        "decision-intelligence"
      ]
    },
    {
      "id": "news-5",
      "slug": "welcome-international-team",
      "title": "HAIR Lab welcomes a growing international team",
      "date": "2025-03-02",
      "author": "Keeheon Lee",
      "authorId": "prof-kim",
      "summary": "Researchers from across the world have joined HAIR Lab to work on human–AI collaboration for social good.",
      "content": "HAIR Lab continues to grow into a truly international team, with members joining from around the world to study human–AI interaction, multi-agent systems, computational social science, and AI ethics. We remain committed to research that creates value beneficial to society.",
      "image": "images/default_news.svg",
      "relatedMembers": [
        "ryu-kunhee",
        "kim-minje",
        "svetasheva-arina",
        "lee-jinho"
      ]
    }
  ],
  "projects": [
    {
      "id": "decision-intelligence",
      "title": "Decision Intelligence: Computational Linguistic Modeling and Evaluation",
      "titleKo": "의사결정 지능: 전산언어적 모델링과 평가",
      "status": "active",
      "type": "National R&D",
      "funder": "Ministry of Science and ICT (MSIT) · NRF Individual Basic Research",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": 2024,
      "endYear": 2027,
      "categories": [
        "National R&D"
      ],
      "description": "A national basic-research program (MSIT/NRF) developing computational-linguistic models and evaluation methods for decision intelligence — how language-based AI can model, support, and assess human and collective decision-making.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": [
        "pub-1",
        "pub-8",
        "pub-9"
      ]
    },
    {
      "id": "visual-understanding-smart-work",
      "title": "Human–Object Interaction-based Visual Understanding for Smart Work",
      "titleKo": "스마트 업무수행을 위한 인간-사물 상호작용 기반 시각 정보 이해",
      "status": "completed",
      "type": "National R&D",
      "funder": "Ministry of Science and ICT (MSIT) · NRF Individual Basic Research",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": 2021,
      "endYear": 2024,
      "categories": [
        "National R&D"
      ],
      "description": "A national basic-research program (MSIT/NRF) on visual information understanding grounded in human–object interaction, toward AI that supports smart work and everyday tasks.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": [
        "pub-12"
      ]
    },
    {
      "id": "tech-society-data-science",
      "title": "Technology–Society Interaction Data Science: A Generative Adversarial Scenario Model for Strategic Learning",
      "titleKo": "기술-사회 상호작용 데이터 사이언스: 전략적 학습을 위한 제너레이티브 대립 시나리오 모형",
      "status": "completed",
      "type": "National R&D",
      "funder": "Ministry of Science and ICT (MSIT) · NRF Young Researcher",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": 2017,
      "endYear": 2020,
      "categories": [
        "National R&D"
      ],
      "description": "An early-career national research program (MSIT/NRF) modeling technology–society interaction with generative adversarial scenario models for strategic learning.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "bio-knowledge-hypothesis",
      "title": "Big-Knowledge-Driven Automatic Hypothesis Inference for New Bio-Knowledge Discovery",
      "titleKo": "거대 지식 그래프 기반 생의학 지식 발견을 위한 자동 가설 추론",
      "status": "completed",
      "type": "National R&D",
      "funder": "Ministry of Science and ICT (MSIT) · NRF Mid-career Research",
      "leadPI": "Min Song",
      "leadPIId": null,
      "startYear": 2019,
      "endYear": 2022,
      "categories": [
        "National R&D"
      ],
      "description": "A national mid-career research program (MSIT/NRF) on automatic hypothesis inference over large knowledge graphs to discover new biomedical knowledge.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "urban-disaster-evacuation",
      "title": "Urban Disaster Evacuation Management and Simulation Program Development",
      "titleKo": "도시 재난 대피 관리 시뮬레이션 프로그램 개발",
      "status": "completed",
      "type": "National R&D",
      "funder": "Ministry of Science and ICT (MSIT) · STEAM Research (EDISON)",
      "leadPI": "Sangwon Lee",
      "leadPIId": null,
      "startYear": 2017,
      "endYear": 2022,
      "categories": [
        "National R&D"
      ],
      "description": "A national STEAM/EDISON research program developing a simulation program for managing urban disaster evacuation.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "medical-doc-extraction",
      "title": "Algorithms and Software for Raw-Data Extraction and Sensitivity Analysis from Medical Documents",
      "titleKo": "의학 관련 문서로부터 원자료 추출 및 민감도 분석 알고리즘과 소프트웨어 개발",
      "status": "completed",
      "type": "SME R&D",
      "funder": "Ministry of SMEs and Startups · Startup Growth Technology Development (Didimdol)",
      "leadPI": "Seongmin Oh",
      "leadPIId": null,
      "startYear": 2021,
      "endYear": 2022,
      "categories": [
        "SME R&D"
      ],
      "description": "An SME technology-development program (Ministry of SMEs and Startups, Didimdol) building algorithms and software to extract raw data and run sensitivity analysis from medical documents.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "kosits-2022-conference",
      "title": "2022 Spring Conference of the Korea Society of IT Services",
      "titleKo": "한국IT서비스학회 2022년 춘계학술대회",
      "status": "completed",
      "type": "Academic Event",
      "funder": "Ministry of Science and ICT (MSIT) · ICT Advancement",
      "leadPI": "Heonyoung Kwon",
      "leadPIId": null,
      "startYear": 2022,
      "endYear": 2022,
      "categories": [
        "Academic Event"
      ],
      "description": "Hosting of the 2022 Spring Conference of the Korea Society of IT Services, supported under an MSIT ICT-advancement program.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "governance-digital-twin",
      "title": "Governance Digital Twin: Agentic Communication Model and Simulation for Democratic Governance",
      "titleKo": "거버넌스 디지털 트윈: 민주적 거버넌스 실험과 평가를 위한 에이전틱 커뮤니케이션 모델 및 시뮬레이션",
      "status": "active",
      "type": "Institutional Research",
      "funder": "Yonsei Institute for AI Innovation (연세AI혁신연구원)",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": null,
      "endYear": null,
      "categories": [
        "Institutional Research"
      ],
      "description": "An institute project at the Yonsei Institute for AI Innovation building an agentic communication model and simulation — a “digital twin” for experimenting with, and evaluating, democratic governance.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": [
        "pub-3",
        "pub-4",
        "pub-5"
      ]
    },
    {
      "id": "tryout-2026",
      "title": "Incheon Startup Park TRYOUT — Global Demonstration (Scale-up Challenge Lab), 2026",
      "titleKo": "2026 인천스타트업파크 TRYOUT 대학 실증사업 — 글로벌 실증(스케일업 챌린지랩)",
      "status": "active",
      "type": "Public Demonstration",
      "funder": "Incheon Economic Free Zone (IFEZ) · Incheon Technopark",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": 2026,
      "endYear": 2026,
      "categories": [
        "Public Demonstration"
      ],
      "description": "A public proof-of-concept and scale-up support program (Incheon Startup Park “TRYOUT” — Scale-up Challenge Lab). The lab leads the Global track, drawing on Yonsei International Campus’ global network to help startups validate their products and expand overseas.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "tryout-2025",
      "title": "Incheon Startup Park TRYOUT — Global Demonstration (Scale-up Challenge Lab), 2025",
      "titleKo": "2025 인천스타트업파크 TRYOUT 대학 실증사업 — 글로벌 실증(스케일업 챌린지랩)",
      "status": "completed",
      "type": "Public Demonstration",
      "funder": "Incheon Economic Free Zone (IFEZ) · Incheon Technopark",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": 2025,
      "endYear": 2025,
      "categories": [
        "Public Demonstration"
      ],
      "description": "A public proof-of-concept and scale-up support program (Incheon Startup Park “TRYOUT” — Scale-up Challenge Lab). The lab leads the Global track, drawing on Yonsei International Campus’ global network to help startups validate their products and expand overseas.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "tryout-2024",
      "title": "Incheon Startup Park TRYOUT — Global Demonstration (Scale-up Challenge Lab), 2024",
      "titleKo": "2024 인천스타트업파크 TRYOUT 대학 실증사업 — 글로벌 실증(스케일업 챌린지랩)",
      "status": "completed",
      "type": "Public Demonstration",
      "funder": "Incheon Economic Free Zone (IFEZ) · Incheon Technopark",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": 2024,
      "endYear": 2024,
      "categories": [
        "Public Demonstration"
      ],
      "description": "A public proof-of-concept and scale-up support program (Incheon Startup Park “TRYOUT” — Scale-up Challenge Lab). The lab leads the Global track, drawing on Yonsei International Campus’ global network to help startups validate their products and expand overseas.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    },
    {
      "id": "tryout-2023",
      "title": "Incheon Startup Park TRYOUT — Global Demonstration (Scale-up Challenge Lab), 2023",
      "titleKo": "2023 인천스타트업파크 TRYOUT 대학 실증사업 — 글로벌 실증(스케일업 챌린지랩)",
      "status": "completed",
      "type": "Public Demonstration",
      "funder": "Incheon Economic Free Zone (IFEZ) · Incheon Technopark",
      "leadPI": "Keeheon Lee",
      "leadPIId": "prof-kim",
      "startYear": 2023,
      "endYear": 2023,
      "categories": [
        "Public Demonstration"
      ],
      "description": "A public proof-of-concept and scale-up support program (Incheon Startup Park “TRYOUT” — Scale-up Challenge Lab). The lab leads the Global track, drawing on Yonsei International Campus’ global network to help startups validate their products and expand overseas.",
      "members": [
        "prof-kim"
      ],
      "image": "images/default_project.svg",
      "website": "#",
      "publications": []
    }
  ],
  "publications": [
    {
      "id": "pub-1",
      "year": 2026,
      "title": "Can Transparency Help Clinicians Trust AI? Reframing Trust as an Information Foraging and Sensemaking Loop",
      "venue": "CHI 2026 Extended Abstracts",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Kunhee Ryu",
          "isMember": true,
          "memberId": "ryu-kunhee"
        },
        {
          "name": "Heeyoung Ghang",
          "isMember": false
        },
        {
          "name": "Sechang Chon",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Younah Kang",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-2",
      "year": 2026,
      "title": "Your Permission Leaks My Data: Second-Hand Privacy Harms in LLM Agents",
      "venue": "CHI 2026 Extended Abstracts",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Minje Kim",
          "isMember": true,
          "memberId": "kim-minje"
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-3",
      "year": 2026,
      "title": "AutoMETA: A Multi-Agent LLM System for Autonomous Meta-Analysis",
      "venue": "AAMAS 2026",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Kunhee Ryu",
          "isMember": true,
          "memberId": "ryu-kunhee"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-4",
      "year": 2026,
      "title": "Manners Maketh MAN: Multi-Agent Norm Dynamics under Cultural Moral Values",
      "venue": "ACM CHI 2026 Workshop on PoliSim",
      "venueType": "Workshop",
      "authors": [
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Kunhee Ryu",
          "isMember": true,
          "memberId": "ryu-kunhee"
        },
        {
          "name": "Minje Kim",
          "isMember": true,
          "memberId": "kim-minje"
        },
        {
          "name": "Hogyun Yoo",
          "isMember": true,
          "memberId": "yoo-hogyun"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-5",
      "year": 2025,
      "title": "Building a consensus: Harmonizing AI ethical guidelines and legal frameworks in Korea for enhanced governance",
      "venue": "Government Information Quarterly",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Jae Woo Lee",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 9,
      "links": {
        "doi": "https://doi.org/10.1016/j.giq.2025.102060"
      }
    },
    {
      "id": "pub-6",
      "year": 2025,
      "title": "Digital Legacy Systems for Young Adults: Emphasizing Relationship-Oriented Perspectives and Physical Artifacts in Death Preparation",
      "venue": "CHI 2025",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Soonho Kwon",
          "isMember": false
        },
        {
          "name": "Hyunah Jo",
          "isMember": false
        },
        {
          "name": "Sohee Ryu",
          "isMember": false
        },
        {
          "name": "Jihwan Ryan Do",
          "isMember": false
        },
        {
          "name": "HwaJung Lee",
          "isMember": false
        },
        {
          "name": "JooHyun Lee",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Younah Kang",
          "isMember": false
        }
      ],
      "citations": 2,
      "links": {}
    },
    {
      "id": "pub-7",
      "year": 2024,
      "title": "“Um, so like, is this how I speak?”: design implications for automated visual feedback systems on speech",
      "venue": "Behaviour & Information Technology",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Soonho Kwon",
          "isMember": false
        },
        {
          "name": "Hyojin Lee",
          "isMember": false
        },
        {
          "name": "Soojeong Park",
          "isMember": false
        },
        {
          "name": "Yerin Heo",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Younah Kang",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {
        "doi": "https://doi.org/10.1080/0144929X.2023.2256770"
      }
    },
    {
      "id": "pub-8",
      "year": 2024,
      "title": "Harnessing Large Language Models for Effective and Efficient Hate Speech Detection",
      "venue": "HICSS 2024",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Arina Svetasheva",
          "isMember": true,
          "memberId": "svetasheva-arina"
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 11,
      "links": {
        "pdf": "https://hdl.handle.net/10125/107216"
      }
    },
    {
      "id": "pub-9",
      "year": 2024,
      "title": "Measuring Falseness in News Articles based on Concealment and Overstatement",
      "venue": "arXiv preprint (arXiv:2408.00156)",
      "venueType": "Preprint",
      "authors": [
        {
          "name": "Jiyoung Lee",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 4,
      "links": {
        "arxiv": "https://arxiv.org/abs/2408.00156"
      }
    },
    {
      "id": "pub-10",
      "year": 2023,
      "title": "The paradigm shift of mass customisation research",
      "venue": "International Journal of Production Research",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Songi Kim",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 59,
      "links": {
        "doi": "https://doi.org/10.1080/00207543.2022.2057256"
      }
    },
    {
      "id": "pub-11",
      "year": 2022,
      "title": "Customization of Roadmap: Human-in-the-Loop Topic Modelling Approach",
      "venue": "PICMET 2022",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Jae Young Ho",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 4,
      "links": {}
    },
    {
      "id": "pub-12",
      "year": 2022,
      "title": "Counting Pixels for an Effective Axis Detection",
      "venue": "IEEE IRI 2022",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Eury Sohn",
          "isMember": false
        },
        {
          "name": "Kunhee Ryu",
          "isMember": true,
          "memberId": "ryu-kunhee"
        },
        {
          "name": "Seongmin Oh",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {
        "doi": "https://doi.org/10.1109/IRI54793.2022.00040"
      }
    },
    {
      "id": "pub-13",
      "year": 2021,
      "title": "A Systematic Review on Social Sustainability of Artificial Intelligence in Product Design",
      "venue": "Sustainability",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 61,
      "links": {
        "doi": "https://doi.org/10.3390/su13052668"
      }
    },
    {
      "id": "pub-14",
      "year": 2021,
      "title": "Deep Learning's Diminishing Returns: The Cost of Improvement is Becoming Unsustainable",
      "venue": "IEEE Spectrum",
      "venueType": "Magazine",
      "authors": [
        {
          "name": "Neil C. Thompson",
          "isMember": false
        },
        {
          "name": "Kristjan Greenewald",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Gabriel F. Manso",
          "isMember": false
        }
      ],
      "citations": 256,
      "links": {
        "doi": "https://doi.org/10.1109/MSPEC.2021.9563954"
      }
    },
    {
      "id": "pub-15",
      "year": 2020,
      "title": "The Computational Limits of Deep Learning",
      "venue": "arXiv preprint (arXiv:2007.05558)",
      "venueType": "Preprint",
      "authors": [
        {
          "name": "Neil C. Thompson",
          "isMember": false
        },
        {
          "name": "Kristjan Greenewald",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Gabriel F. Manso",
          "isMember": false
        }
      ],
      "citations": 1249,
      "links": {
        "arxiv": "https://arxiv.org/abs/2007.05558"
      }
    },
    {
      "id": "pub-16",
      "year": 2020,
      "title": "Simple and Steady Interactions Win the Healthy Mentality: Designing a Chatbot Service for the Elderly",
      "venue": "Proceedings of the ACM on Human-Computer Interaction (CSCW2)",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Hyeyoung Ryu",
          "isMember": false
        },
        {
          "name": "Soyeon Kim",
          "isMember": false
        },
        {
          "name": "Dain Kim",
          "isMember": false
        },
        {
          "name": "Sooan Han",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Younah Kang",
          "isMember": false
        }
      ],
      "citations": 98,
      "links": {
        "doi": "https://doi.org/10.1145/3415223"
      }
    },
    {
      "id": "pub-17",
      "year": 2020,
      "title": "Dynamic semantic network analysis for identifying the concept and scope of social sustainability",
      "venue": "Journal of Cleaner Production",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Heejun Jung",
          "isMember": false
        }
      ],
      "citations": 97,
      "links": {
        "doi": "https://doi.org/10.1016/j.jclepro.2019.07.060"
      }
    },
    {
      "id": "pub-18",
      "year": 2020,
      "title": "Designing technology entrepreneurship education using computational thinking",
      "venue": "Education and Information Technologies",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Younah Kang",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 48,
      "links": {
        "doi": "https://doi.org/10.1007/s10639-020-10231-2"
      }
    },
    {
      "id": "pub-19",
      "year": 2020,
      "title": "Building Ethical AI from News Articles",
      "venue": "IEEE/ITU AI for Good (AI4G) 2020",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Wonjun Kim",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 4,
      "links": {}
    },
    {
      "id": "pub-20",
      "year": 2019,
      "title": "Can Chatbots Help Reduce the Workload of Administrative Officers? Implementing and Deploying FAQ Chatbot Service in a University",
      "venue": "HCI International 2019",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Jeongmin Jo",
          "isMember": false
        },
        {
          "name": "Jinwoo Kim",
          "isMember": false
        },
        {
          "name": "Younah Kang",
          "isMember": false
        }
      ],
      "citations": 71,
      "links": {
        "doi": "https://doi.org/10.1007/978-3-030-23528-4_46"
      }
    },
    {
      "id": "pub-21",
      "year": 2019,
      "title": "A Data-Driven Design Framework for Customer Service Chatbot",
      "venue": "HCI International 2019",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "Shinhee Hwang",
          "isMember": false
        },
        {
          "name": "Beomjun Kim",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 36,
      "links": {
        "doi": "https://doi.org/10.1007/978-3-030-22577-3_16"
      }
    },
    {
      "id": "pub-22",
      "year": 2019,
      "title": "Agent simulation-based ordinal optimisation for new product design",
      "venue": "Journal of the Operational Research Society",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Hoyeop Lee",
          "isMember": false
        },
        {
          "name": "Jongsu Lim",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Chang Ouk Kim",
          "isMember": false
        }
      ],
      "citations": 10,
      "links": {
        "doi": "https://doi.org/10.1080/01605682.2018.1447249"
      }
    },
    {
      "id": "pub-23",
      "year": 2018,
      "title": "Factors that influence an individual's intention to adopt a wearable healthcare device: The case of a wearable fitness tracker",
      "venue": "Technological Forecasting and Social Change",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Sang Yup Lee",
          "isMember": false
        },
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 244,
      "links": {
        "doi": "https://doi.org/10.1016/j.techfore.2018.01.022"
      }
    },
    {
      "id": "pub-24",
      "year": 2016,
      "title": "Subject–method topic network analysis in communication studies",
      "venue": "Scientometrics",
      "venueType": "Journal",
      "authors": [
        {
          "name": "Keeheon Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Heejun Jung",
          "isMember": false
        },
        {
          "name": "Min Song",
          "isMember": false
        }
      ],
      "citations": 49,
      "links": {
        "doi": "https://doi.org/10.1007/s11192-016-2100-5"
      }
    },
    {
      "id": "pub-25",
      "year": 2026,
      "title": "From Higher-Likelihood to Broader Coverage: Exploratory Policy Simulations with LLM agents",
      "venue": "ACM CHI 2026 Workshop on PoliSim",
      "venueType": "Workshop",
      "authors": [
        {
          "name": "Hogyun Yoo",
          "isMember": true,
          "memberId": "yoo-hogyun"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-26",
      "year": 2026,
      "title": "TIRA: Technical Indicator-based Retrieval Augmentation for Large Language Model-driven Stock Trading",
      "venue": "2nd Workshop on Advances in Financial AI",
      "venueType": "Workshop",
      "authors": [
        {
          "name": "M Kim",
          "isMember": true,
          "memberId": "kim-minje"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "CG Lee",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-27",
      "year": 2026,
      "title": "Student Scholarly Research Programs in US Medical Schools: Cross-sectional Web Audit",
      "venue": "medRxiv",
      "venueType": "Preprint",
      "authors": [
        {
          "name": "D Lee",
          "isMember": false
        },
        {
          "name": "C Lee",
          "isMember": false
        },
        {
          "name": "SS Oh",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "CS Hyun",
          "isMember": false
        },
        {
          "name": "JI Shin",
          "isMember": false
        },
        {
          "name": "S An",
          "isMember": false
        },
        {
          "name": "J Ioannidis",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-28",
      "year": 2026,
      "title": "Evolution of Reporting P-values Across the Biomedical Literature, 1990–2025",
      "venue": "medRxiv",
      "venueType": "Preprint",
      "authors": [
        {
          "name": "J Choi",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "D Chavalarias",
          "isMember": false
        },
        {
          "name": "JI Shin",
          "isMember": false
        },
        {
          "name": "J Ioannidis",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-29",
      "year": 2025,
      "title": "대학 웹사이트에 인공지능 기능을 도입한 사용자 중심 디자인 개선 방안 연구",
      "venue": "대한산업공학회 추계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "H Ghang",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-30",
      "year": 2025,
      "title": "From Bullwhip to Hallucination: Quantifying and Mitigating Error Amplification in Large Language Models",
      "venue": "대한산업공학회 춘계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "K Ryu",
          "isMember": true,
          "memberId": "ryu-kunhee"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-31",
      "year": 2025,
      "title": "전략 시뮬레이션게임에서의 의사결정 네트워크 분석",
      "venue": "대한산업공학회 춘계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "H Kim",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-32",
      "year": 2025,
      "title": "컨텍스트 한계를 넘어: 에이전트 역할 분리를 통한 Self-Refine 파이프라인 개선",
      "venue": "대한산업공학회 춘계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "H Kim",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-33",
      "year": 2025,
      "title": "Analysis of Decision-Support Modules for LLM-Based Online Sequential Decision Making",
      "venue": "대한산업공학회 춘계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "M Kim",
          "isMember": true,
          "memberId": "kim-minje"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-34",
      "year": 2025,
      "title": "이탈리안 브레인롯의 진화",
      "venue": "한국IT서비스학회 학술대회",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "H Kim",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-35",
      "year": 2025,
      "title": "자율주행차 디지털 포렌식 기술의 혁신 분석",
      "venue": "경찰학연구 25(1)",
      "venueType": "Domestic Journal",
      "authors": [
        {
          "name": "S Ra",
          "isMember": false
        },
        {
          "name": "M Kim",
          "isMember": true,
          "memberId": "kim-minje"
        },
        {
          "name": "C Yoon",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-36",
      "year": 2025,
      "title": "Analysis of Technological Innovations in Stock Trading Using a Language Model",
      "venue": "SSRN 5105531",
      "venueType": "Preprint",
      "authors": [
        {
          "name": "M Kim",
          "isMember": true,
          "memberId": "kim-minje"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 1,
      "links": {
        "link": "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5105531"
      }
    },
    {
      "id": "pub-37",
      "year": 2024,
      "title": "From Uncanny to Unison: Entertainment Professionals' Perceptions of Singing Voice Synthesis",
      "venue": "한국HCI학회 학술대회",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "GM Arumsari",
          "isMember": false
        },
        {
          "name": "KH Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "D Kim",
          "isMember": false
        },
        {
          "name": "FM Lim",
          "isMember": false
        },
        {
          "name": "S Almatari",
          "isMember": false
        },
        {
          "name": "TP Vu",
          "isMember": false
        }
      ],
      "citations": 2,
      "links": {}
    },
    {
      "id": "pub-38",
      "year": 2024,
      "title": "The Network Position of AI Venture Companies in Investment Network",
      "venue": "2024 Portland International Conference on Management of Engineering and Technology (PICMET)",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "B Kim",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-39",
      "year": 2024,
      "title": "Waning Breakthroughs? Investigating the State of Innovation in the Field of NLP",
      "venue": "2024 Portland International Conference on Management of Engineering and Technology (PICMET)",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "A Gasparini",
          "isMember": true,
          "memberId": "gasparini-abebe"
        },
        {
          "name": "CH Lohmander",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-40",
      "year": 2024,
      "title": "Measuring Diversity and Fairness in Content Exposure: Case of Instagram Recommender System",
      "venue": "한국HCI학회 학술대회",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "S Kim",
          "isMember": false
        },
        {
          "name": "A Svetasheva",
          "isMember": true,
          "memberId": "svetasheva-arina"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Y Kang",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-41",
      "year": 2024,
      "title": "Establishing the ESD and GCEd system in higher education",
      "venue": "IGEE Proceedings 1(1)",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "JE Shin",
          "isMember": false
        },
        {
          "name": "EK Rhee",
          "isMember": false
        },
        {
          "name": "S An",
          "isMember": false
        },
        {
          "name": "Y Kang",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "IH Song",
          "isMember": false
        }
      ],
      "citations": 1,
      "links": {}
    },
    {
      "id": "pub-42",
      "year": 2023,
      "title": "Methods and Evaluation in the Historical Mapping of Cities",
      "venue": "International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "M Page",
          "isMember": false
        },
        {
          "name": "Y Kang",
          "isMember": false
        },
        {
          "name": "S Varner",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "A Cors",
          "isMember": false
        },
        {
          "name": "A Basu",
          "isMember": false
        },
        {
          "name": "K Durante",
          "isMember": false
        },
        {
          "name": "I Burr",
          "isMember": false
        }
      ],
      "citations": 2,
      "links": {}
    },
    {
      "id": "pub-43",
      "year": 2023,
      "title": "프롬프트 엔지니어링을 활용한 기업 재무제표 평가 및 성능 비교",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "김민제",
          "isMember": true,
          "memberId": "kim-minje"
        },
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 1,
      "links": {}
    },
    {
      "id": "pub-44",
      "year": 2023,
      "title": "Query Optimization Information Retrieval Framework Using a Wikipedia-Based Vector Database",
      "venue": "대한산업공학회 추계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "K Ryu",
          "isMember": true,
          "memberId": "ryu-kunhee"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-45",
      "year": 2023,
      "title": "Comparative Sentiment Analysis of World-renowned Landmarks",
      "venue": "대한산업공학회 추계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "A Gasparini",
          "isMember": true,
          "memberId": "gasparini-abebe"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-46",
      "year": 2023,
      "title": "Mimicking Experts: Evaluating Response Qualities of ChatGPT in Technology Forecasting and UI/UX fields",
      "venue": "대한산업공학회 추계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "JW Lee",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-47",
      "year": 2023,
      "title": "Automating Academic Tasks with ChatGPT: A Usability Study",
      "venue": "대한산업공학회 추계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "JW Lee",
          "isMember": false
        },
        {
          "name": "A Svetasheva",
          "isMember": true,
          "memberId": "svetasheva-arina"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-48",
      "year": 2023,
      "title": "Large Language Model and Discrete Event Simulation for Health Care: Severity Classification in Triage",
      "venue": "대한산업공학회 추계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "Z Daniar",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-49",
      "year": 2023,
      "title": "A Systematic Review on Predict-then-Optimize",
      "venue": "대한산업공학회 추계학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "H Kim",
          "isMember": false
        },
        {
          "name": "S Lee",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-50",
      "year": 2023,
      "title": "Sarcasm Classification: Cost/Benefit Analysis of Few-shot Prompting GPT-3",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "J Kim",
          "isMember": false
        },
        {
          "name": "J Jang",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-51",
      "year": 2023,
      "title": "Exploring the Characteristics of Large-Scale Text to Image Prompt Datasets",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "S Song",
          "isMember": false
        },
        {
          "name": "Y Kang",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-52",
      "year": 2023,
      "title": "On the Use of Prompt Engineering for Research Purposes",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "A Gasparini",
          "isMember": true,
          "memberId": "gasparini-abebe"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-53",
      "year": 2023,
      "title": "Large Language Model for Healthcare: Severity Classification in Triage",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "Z Daniar",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-54",
      "year": 2023,
      "title": "LLMs Improve Automatic Hate Speech Detection Efficiently and Effectively",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "A Svetasheva",
          "isMember": true,
          "memberId": "svetasheva-arina"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-55",
      "year": 2023,
      "title": "생성형 검색 엔진에서의 프롬프트 최적화를 통한 정보 검색",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "K Ryu",
          "isMember": true,
          "memberId": "ryu-kunhee"
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-56",
      "year": 2023,
      "title": "연구 동향 분석을 위한 대형 언어 모델의 프롬프트 디자인 제안",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "안재연",
          "isMember": false
        },
        {
          "name": "강연아",
          "isMember": false
        },
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-57",
      "year": 2023,
      "title": "디지털 정부 정책 텍스트 분석을 통한 기술 트렌드의 동향 파악 및 전망",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "김혜강",
          "isMember": false
        },
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-58",
      "year": 2023,
      "title": "Large Language Models as Potential Interviewees: Focused on ChatGPT",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "J Lee",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-59",
      "year": 2023,
      "title": "Evaluation of Korean Industrial Engineering Research based on Sustainable Development",
      "venue": "대한산업공학회 춘계공동학술대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "H Lohmander",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-60",
      "year": 2021,
      "title": "Pillip and MyPillip: For Simple and Personalized Pill Consumption Process",
      "venue": "한국디자인학회 학술발표대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "D Kim",
          "isMember": false
        },
        {
          "name": "E Sohn",
          "isMember": false
        },
        {
          "name": "J Wong",
          "isMember": false
        },
        {
          "name": "J Han",
          "isMember": false
        },
        {
          "name": "Y Lin",
          "isMember": false
        },
        {
          "name": "Y Kang",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-61",
      "year": 2021,
      "title": "UIUX Optimization for Senior",
      "venue": "한국디자인학회 학술발표대회 논문집",
      "venueType": "Domestic Conference",
      "authors": [
        {
          "name": "J Oh",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "H Lee",
          "isMember": false
        },
        {
          "name": "S Lee",
          "isMember": false
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-62",
      "year": 2021,
      "title": "Display Ad Classifier: Quantifying Annoying Ad Practices and Its Effect on Website Popularity",
      "venue": "2021 AMA Winter Academic Conference",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "S Hong",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-63",
      "year": 2020,
      "title": "역사 학습효과 증진을 위한 웹 가상박물관 디자인 가이드라인에 대한 연구",
      "venue": "박물관학보",
      "venueType": "Domestic Journal",
      "authors": [
        {
          "name": "이다빈",
          "isMember": false
        },
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 2,
      "links": {}
    },
    {
      "id": "pub-64",
      "year": 2020,
      "title": "한국 언론기사를 대규모 역사데이터로 활용한 동북아 해양영토분쟁 분석",
      "venue": "국제지역연구 24(2)",
      "venueType": "Domestic Journal",
      "authors": [
        {
          "name": "양준석",
          "isMember": false
        },
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "조화순",
          "isMember": false
        }
      ],
      "citations": 1,
      "links": {}
    },
    {
      "id": "pub-65",
      "year": 2019,
      "title": "A Data-Driven Strategic Model of Common Sense in Machine Ethics of Cares",
      "venue": "HCI International 2019",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "W Kim",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 2,
      "links": {}
    },
    {
      "id": "pub-66",
      "year": 2019,
      "title": "Transforming a Specialized Q&A System to a Chatbot System: A Case of a Simplified Process",
      "venue": "HCI International 2019 – Late Breaking Posters",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "J Jang",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 6,
      "links": {}
    },
    {
      "id": "pub-67",
      "year": 2019,
      "title": "An Online Comment Assistant for a Better Comment Experience",
      "venue": "HCI International 2019 – Late Breaking Posters",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "JY Choi",
          "isMember": false
        },
        {
          "name": "Y Kang",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-68",
      "year": 2019,
      "title": "Guidelines for Evaluating the Completeness of the Portfolio",
      "venue": "HCI International 2019",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "JM Ryu",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": null,
      "links": {}
    },
    {
      "id": "pub-69",
      "year": 2019,
      "title": "Bringing Computational Thinking to Nonengineering Students through a Capstone Course",
      "venue": "52nd Hawaii International Conference on System Sciences (HICSS)",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "Y Kang",
          "isMember": false
        }
      ],
      "citations": 4,
      "links": {
        "link": "https://scholarspace.manoa.hawaii.edu/items/00b41fe5-0c4f-4518-a863-ed6b6d5af65a"
      }
    },
    {
      "id": "pub-70",
      "year": 2017,
      "title": "Ensemble analysis of topical journal ranking in bioinformatics",
      "venue": "Journal of the Association for Information Science and Technology 68(6)",
      "venueType": "Journal",
      "authors": [
        {
          "name": "M Song",
          "isMember": false
        },
        {
          "name": "SY Kim",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 11,
      "links": {}
    },
    {
      "id": "pub-71",
      "year": 2017,
      "title": "Comparative evaluation of bibliometric content networks by tomographic content analysis",
      "venue": "Journal of the Association for Information Science and Technology 68(5)",
      "venueType": "Journal",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "SY Kim",
          "isMember": false
        },
        {
          "name": "EHJ Kim",
          "isMember": false
        },
        {
          "name": "M Song",
          "isMember": false
        }
      ],
      "citations": 10,
      "links": {}
    },
    {
      "id": "pub-72",
      "year": 2016,
      "title": "Examining Characteristics of Traditional and Twitter Citation",
      "venue": "Frontiers in Research Metrics and Analytics 1",
      "venueType": "Journal",
      "authors": [
        {
          "name": "H Jung",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "M Song",
          "isMember": false
        }
      ],
      "citations": 18,
      "links": {}
    },
    {
      "id": "pub-73",
      "year": 2015,
      "title": "문헌정보학 분야 핵심 학술지들의 가중 주제-방법 네트워크 분석",
      "venue": "한국문헌정보학회지",
      "venueType": "Domestic Journal",
      "authors": [
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "정효정",
          "isMember": false
        },
        {
          "name": "송민",
          "isMember": false
        }
      ],
      "citations": 20,
      "links": {}
    },
    {
      "id": "pub-74",
      "year": 2015,
      "title": "행위자기반모형을 이용한 신기술과 지식 확산 연구",
      "venue": "조사연구",
      "venueType": "Domestic Journal",
      "authors": [
        {
          "name": "이상엽",
          "isMember": false
        },
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 1,
      "links": {}
    },
    {
      "id": "pub-75",
      "year": 2015,
      "title": "Comparing Network Structures of Different Versions of a Book",
      "venue": "International Conference on Asian Digital Libraries (ICADL)",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        }
      ],
      "citations": 2,
      "links": {}
    },
    {
      "id": "pub-76",
      "year": 2015,
      "title": "Analyzing Subject-Method Network of Bioinformatics and Biology",
      "venue": "ACM 9th International Workshop on Data and Text Mining in Biomedical Informatics (DTMBIO)",
      "venueType": "Workshop",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "YH Kim",
          "isMember": false
        },
        {
          "name": "SH Baek",
          "isMember": false
        },
        {
          "name": "M Song",
          "isMember": false
        }
      ],
      "citations": 2,
      "links": {}
    },
    {
      "id": "pub-77",
      "year": 2014,
      "title": "Inferring Undiscovered Public Knowledge by Using Text Mining-driven Graph Model",
      "venue": "ACM 8th International Workshop on Data and Text Mining in Biomedical Informatics (DTMBIO)",
      "venueType": "Workshop",
      "authors": [
        {
          "name": "GE Heo",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "M Song",
          "isMember": false
        }
      ],
      "citations": 8,
      "links": {}
    },
    {
      "id": "pub-78",
      "year": 2014,
      "title": "Pricing and Timing Strategies for New Product Using Agent-Based Simulation",
      "venue": "Journal of Artificial Societies and Social Simulation 17(2)",
      "venueType": "Journal",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "H Lee",
          "isMember": false
        },
        {
          "name": "CO Kim",
          "isMember": false
        }
      ],
      "citations": 26,
      "links": {}
    },
    {
      "id": "pub-79",
      "year": 2014,
      "title": "Topic Recipe-based Social Simulation for Research Dynamics Analysis",
      "venue": "Social Simulation Conference (SSC)",
      "venueType": "International Conference",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "CO Kim",
          "isMember": false
        }
      ],
      "citations": 1,
      "links": {}
    },
    {
      "id": "pub-80",
      "year": 2013,
      "title": "An Agent-Based Competitive Product Diffusion Model for the Estimation and Sensitivity Analysis",
      "venue": "Journal of Artificial Societies and Social Simulation 16(1)",
      "venueType": "Journal",
      "authors": [
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "S Kim",
          "isMember": false
        },
        {
          "name": "CO Kim",
          "isMember": false
        },
        {
          "name": "T Park",
          "isMember": false
        }
      ],
      "citations": 28,
      "links": {}
    },
    {
      "id": "pub-81",
      "year": 2011,
      "title": "Agent-based diffusion model for an automobile market with fuzzy TOPSIS-based product adoption process",
      "venue": "Expert Systems with Applications 38(6)",
      "venueType": "Journal",
      "authors": [
        {
          "name": "S Kim",
          "isMember": false
        },
        {
          "name": "K Lee",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "JK Cho",
          "isMember": false
        },
        {
          "name": "CO Kim",
          "isMember": false
        }
      ],
      "citations": 119,
      "links": {}
    },
    {
      "id": "pub-82",
      "year": 2009,
      "title": "원저: 종합병원 응급실 대상의 맞춤형 과밀도 지표 개발",
      "venue": "대한응급의학회지 20(4)",
      "venueType": "Domestic Journal",
      "authors": [
        {
          "name": "고종명",
          "isMember": false
        },
        {
          "name": "손지훈",
          "isMember": false
        },
        {
          "name": "안용덕",
          "isMember": false
        },
        {
          "name": "이기헌",
          "isMember": true,
          "memberId": "prof-kim"
        },
        {
          "name": "양승환",
          "isMember": false
        },
        {
          "name": "김승호",
          "isMember": false
        },
        {
          "name": "박유석",
          "isMember": false
        },
        {
          "name": "이영훈",
          "isMember": false
        }
      ],
      "citations": 1,
      "links": {}
    }
  ],
  "alumni": [
    {
      "name": "Dongkyu Lee",
      "nameKo": "이동규",
      "cohort": "CTM '12",
      "now": "LG AI Research — Ph.D. in Computer Science, HKUST; previously interned at Amazon"
    },
    {
      "name": "Haksong Lim",
      "nameKo": "임학송",
      "cohort": "CTM '12",
      "now": "Resera Capital — M.S. in Business Analytics, Columbia University"
    },
    {
      "name": "Jaekeun Lee",
      "nameKo": "이재근",
      "cohort": "CTM '13",
      "now": "AI Solution Dept., NH Investment & Securities — M.S. in Data Science, UBC"
    },
    {
      "name": "Hayoung Cho",
      "nameKo": "조하영",
      "cohort": "CTM '14",
      "now": "Freddie Mac — M.S. in Applied Analytics, Columbia University"
    },
    {
      "name": "Jeongwon Jo",
      "nameKo": "조정원",
      "cohort": "CTM '15",
      "now": "Ph.D. candidate, Information Science & Technology, Penn State University (adv. John Carroll)"
    },
    {
      "name": "Seokhyun Hong",
      "nameKo": "홍석현",
      "cohort": "CTM '15",
      "now": "Hyperconnect — previously Flitto"
    },
    {
      "name": "Jaeyi Joo",
      "nameKo": "주재이",
      "cohort": "CTM '15",
      "now": "Yonsei University (adv. Sungjoo Bae)"
    },
    {
      "name": "Jiyun Kim",
      "nameKo": "김지윤",
      "cohort": "CTM '15",
      "now": ""
    },
    {
      "name": "James Jinwoo Han",
      "nameKo": "한진우",
      "cohort": "CTM '15",
      "now": ""
    },
    {
      "name": "Kylie Trinh",
      "nameKo": "",
      "cohort": "CTM '15",
      "now": "Business Intelligence, Shopee"
    },
    {
      "name": "Sooan Han",
      "nameKo": "한수안",
      "cohort": "CTM '16",
      "now": ""
    },
    {
      "name": "Hyeyoung Ryu",
      "nameKo": "류혜영",
      "cohort": "CTM '16",
      "now": "Ph.D. student, Information Science (Biomedical & Health Informatics), University of Washington (adv. Wanda Pratt)"
    },
    {
      "name": "Hannes Lohmander",
      "nameKo": "",
      "cohort": "CTM '17",
      "now": "Entrepreneur, Andas.ai — M.S. in Innovation, Yonsei University"
    },
    {
      "name": "Seungjin Lee",
      "nameKo": "이승진",
      "cohort": "CTM '17",
      "now": "SK On — Manager, EV Battery Marketing (US)"
    },
    {
      "name": "Juwon Shin",
      "nameKo": "신주원",
      "cohort": "CTM '17",
      "now": "UNESCO APCEIU — M.S. in International Education Development, University of Pennsylvania"
    },
    {
      "name": "Wonchul Kim",
      "nameKo": "김원철",
      "cohort": "DI '18",
      "now": "Makerspace i7 — M.S. in Design Intelligence"
    },
    {
      "name": "Jaewoo Lee",
      "nameKo": "이재우",
      "cohort": "STP '18",
      "now": "Ph.D. student, University of Cambridge"
    },
    {
      "name": "Hyegang Kim",
      "nameKo": "김혜강",
      "cohort": "CTM '18 · M.S. Innovation",
      "now": "Ph.D. student, University of Toronto"
    },
    {
      "name": "Zahra Namira Daniar",
      "nameKo": "",
      "cohort": "M.S. Innovation",
      "now": ""
    },
    {
      "name": "Galih Mekar Arumsari",
      "nameKo": "",
      "cohort": "M.S. Innovation",
      "now": ""
    },
    {
      "name": "Seoyeon Lee",
      "nameKo": "이서연",
      "cohort": "CTM '21",
      "now": "Graduate School of Law, Yonsei University"
    }
  ]
};
